export const ROLES = {
  FOUNDER: 'FOUNDER',
  CO_FOUNDER: 'CO_FOUNDER',
  MANAGER: 'MANAGER',
  AGGREGATOR: 'AGGREGATOR',
  STORE: 'STORE',
  MASTAN_HEAD: 'MASTAN_HEAD',
  DELUXE_HEAD: 'DELUXE_HEAD',
  TAILOR_MASTER: 'TAILOR_MASTER',
  MACHINE_EMB: 'MACHINE_EMB',
  HAND_EMB: 'HAND_EMB',
  TAILOR_STITCH: 'TAILOR_STITCH',
  CHECKER: 'CHECKER',
  FINISHER: 'FINISHER',
  PACKER: 'PACKER',
  COURIER: 'COURIER',
};

// SaaS Hierarchy: Kaun kisko invite kar sakta hai
export const HIERARCHY = {
  [ROLES.FOUNDER]: [ROLES.CO_FOUNDER, ROLES.STORE],
  [ROLES.CO_FOUNDER]: [ROLES.MANAGER, ROLES.AGGREGATOR, ROLES.PACKER, ROLES.COURIER],
  [ROLES.MANAGER]: [ROLES.AGGREGATOR, ROLES.STORE],
  [ROLES.AGGREGATOR]: [ROLES.MASTAN_HEAD, ROLES.DELUXE_HEAD, ROLES.FINISHER],
  [ROLES.MASTAN_HEAD]: [ROLES.TAILOR_MASTER, ROLES.TAILOR_STITCH, ROLES.CHECKER],
  [ROLES.DELUXE_HEAD]: [ROLES.TAILOR_MASTER, ROLES.TAILOR_STITCH, ROLES.CHECKER],
  // Embs usually common, maybe invited by Manager
  [ROLES.MANAGER]: [ROLES.MACHINE_EMB, ROLES.HAND_EMB, ROLES.CHECKER],
};