export const ROLES = {
  FOUNDER: 'FOUNDER',
  CO_FOUNDER: 'CO_FOUNDER',
  MANAGER: 'MANAGER',
  AGGREGATOR: 'AGGREGATOR',
  MASTAN_HEAD: 'MASTAN_HEAD',
  DELUXE_HEAD: 'DELUXE_HEAD',
  TAILOR_MASTER: 'TAILOR_MASTER',
  MACHINE_EMB: 'MACHINE_EMB',
  HAND_EMB: 'HAND_EMB',
  TAILOR_STITCH: 'TAILOR_STITCH',
  CHECKER: 'CHECKER',
  FINISHER: 'FINISHER',
  PACKER: 'PACKER',
};

// SaaS Hierarchy: Kaun kisko invite kar sakta hai
export const HIERARCHY = {
  [ROLES.FOUNDER]: [ROLES.CO_FOUNDER],
  [ROLES.CO_FOUNDER]: [ROLES.MANAGER, ROLES.AGGREGATOR],
  [ROLES.AGGREGATOR]: [ROLES.MASTAN_HEAD, ROLES.DELUXE_HEAD],
  [ROLES.MASTAN_HEAD]: [ROLES.TAILOR_MASTER, ROLES.TAILOR_STITCH],
  [ROLES.DELUXE_HEAD]: [ROLES.TAILOR_MASTER, ROLES.TAILOR_STITCH],
};